# Generated by Django 2.0 on 2018-01-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_name', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=45, verbose_name='Название отеля')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id_human', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Nomer',
            fields=[
                ('id_nomera', models.AutoField(primary_key=True, serialize=False)),
                ('kod_nomera', models.CharField(max_length=45, verbose_name='Код номера')),
                ('hotell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Registr',
            fields=[
                ('id_registr', models.AutoField(primary_key=True, serialize=False)),
                ('code_registr', models.CharField(max_length=45, verbose_name='Код регистрации')),
                ('nomer_registr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Nomer', verbose_name='Выбранная комната')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.AddField(
            model_name='human',
            name='registr_code',
            field=models.ManyToManyField(to='my_app.Registr', verbose_name='Код регистрации'),
        ),
    ]
